// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rock288/go-mongo-boilerplate/internal/platform/config"
	"github.com/rock288/go-mongo-boilerplate/internal/platform/logger"
	"github.com/rock288/go-mongo-boilerplate/internal/user"
)

// Injectors from wire.go:

func InitializeWorker(cfgPath string) (*WorkerApp, func(), error) {
	configConfig, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := ProvideLoggerConfig(configConfig)
	slogLogger := logger.New(loggerConfig)
	kafkaConfig := ProvideKafkaConfig(configConfig)
	mainClient, cleanup, err := ProvideMainConsumer(kafkaConfig)
	if err != nil {
		return nil, nil, err
	}
	retryClient, cleanup2, err := ProvideRetryConsumer(kafkaConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	producerClient, cleanup3, err := ProvideProducerClient(kafkaConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	producer := ProvideProducer(producerClient)
	eventHandler := user.NewEventHandler(slogLogger)
	messageHandler := ProvideMessageHandler(eventHandler)
	sqsConfig := ProvideSQSConfig(configConfig)
	sqsClient, cleanup4, err := ProvideSQSClient(sqsConfig)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sqsProducer := ProvideSQSProducer(sqsClient)
	sqsMessageHandler := ProvideSQSHandler()
	sqsChecker := ProvideSQSChecker()
	kafkaChecker := ProvideKafkaChecker()
	registry := ProvideHealthRegistry(kafkaChecker, sqsChecker, configConfig)
	observabilityConfig := ProvideObservabilityConfig(configConfig)
	shutdown, cleanup5, err := ProvideObservability(observabilityConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workerApp := &WorkerApp{
		Config:       configConfig,
		Logger:       slogLogger,
		MainClient:   mainClient,
		RetryClient:  retryClient,
		Producer:     producer,
		Handler:      messageHandler,
		SQSClient:    sqsClient,
		SQSProducer:  sqsProducer,
		SQSHandler:   sqsMessageHandler,
		SQSChecker:   sqsChecker,
		Health:       registry,
		KafkaChecker: kafkaChecker,
		Shutdown:     shutdown,
	}
	return workerApp, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
