// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/rock288/go-mongo-boilerplate/internal/platform/config"
	"github.com/rock288/go-mongo-boilerplate/internal/platform/logger"
	"github.com/rock288/go-mongo-boilerplate/internal/user"
)

// Injectors from wire.go:

func InitializeWorker(cfgPath string) (*WorkerApp, func(), error) {
	configConfig, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	observabilityConfig := ProvideObservabilityConfig(configConfig)
	shutdown, cleanupObs, err := ProvideObservability(observabilityConfig)
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := ProvideLoggerConfig(configConfig)
	slogLogger := logger.New(loggerConfig)
	kafkaConfig := ProvideKafkaConfig(configConfig)
	mainClient, cleanupMain, err := ProvideMainConsumer(kafkaConfig)
	if err != nil {
		cleanupObs()
		return nil, nil, err
	}
	retryClient, cleanupRetry, err := ProvideRetryConsumer(kafkaConfig)
	if err != nil {
		cleanupMain()
		cleanupObs()
		return nil, nil, err
	}
	producerClient, cleanupProducer, err := ProvideProducerClient(kafkaConfig)
	if err != nil {
		cleanupRetry()
		cleanupMain()
		cleanupObs()
		return nil, nil, err
	}
	producer := ProvideProducer(producerClient)
	eventHandler := user.NewEventHandler(slogLogger)
	messageHandler := ProvideMessageHandler(eventHandler)
	kafkaChecker := ProvideKafkaChecker()
	registry := ProvideHealthRegistry(kafkaChecker)
	workerApp := &WorkerApp{
		Config:       configConfig,
		Logger:       slogLogger,
		MainClient:   mainClient,
		RetryClient:  retryClient,
		Producer:     producer,
		Handler:      messageHandler,
		Health:       registry,
		KafkaChecker: kafkaChecker,
		Shutdown:     shutdown,
	}
	return workerApp, func() {
		cleanupProducer()
		cleanupRetry()
		cleanupMain()
		cleanupObs()
	}, nil
}
