// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rock288/go-mongo-boilerplate/internal/platform/pagination"
	"github.com/rock288/go-mongo-boilerplate/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type UserService
func (_mock *UserService) List(ctx context.Context, cursor string, limit int) (pagination.Page[user.UserResponse], error) {
	ret := _mock.Called(ctx, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 pagination.Page[user.UserResponse]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (pagination.Page[user.UserResponse], error)); ok {
		return returnFunc(ctx, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) pagination.Page[user.UserResponse]); ok {
		r0 = returnFunc(ctx, cursor, limit)
	} else {
		r0 = ret.Get(0).(pagination.Page[user.UserResponse])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - cursor string
//   - limit int
func (_e *UserService_Expecter) List(ctx interface{}, cursor interface{}, limit interface{}) *UserService_List_Call {
	return &UserService_List_Call{Call: _e.mock.On("List", ctx, cursor, limit)}
}

func (_c *UserService_List_Call) Run(run func(ctx context.Context, cursor string, limit int)) *UserService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserService_List_Call) Return(page pagination.Page[user.UserResponse], err error) *UserService_List_Call {
	_c.Call.Return(page, err)
	return _c
}

func (_c *UserService_List_Call) RunAndReturn(run func(ctx context.Context, cursor string, limit int) (pagination.Page[user.UserResponse], error)) *UserService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type UserService
func (_mock *UserService) Register(ctx context.Context, req user.RegisterRequest) (*user.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.RegisterRequest) (*user.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.RegisterRequest) *user.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.RegisterRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.RegisterRequest
func (_e *UserService_Expecter) Register(ctx interface{}, req interface{}) *UserService_Register_Call {
	return &UserService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *UserService_Register_Call) Run(run func(ctx context.Context, req user.RegisterRequest)) *UserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.RegisterRequest
		if args[1] != nil {
			arg1 = args[1].(user.RegisterRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_Register_Call) Return(user1 *user.User, err error) *UserService_Register_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserService_Register_Call) RunAndReturn(run func(ctx context.Context, req user.RegisterRequest) (*user.User, error)) *UserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
