// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rock288/go-mongo-boilerplate/internal/role"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleService creates a new instance of RoleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleService {
	mock := &RoleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleService is an autogenerated mock type for the RoleService type
type RoleService struct {
	mock.Mock
}

type RoleService_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleService) EXPECT() *RoleService_Expecter {
	return &RoleService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RoleService
func (_mock *RoleService) Create(ctx context.Context, req role.CreateRoleRequest) (*role.Role, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, role.CreateRoleRequest) (*role.Role, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, role.CreateRoleRequest) *role.Role); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, role.CreateRoleRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RoleService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req role.CreateRoleRequest
func (_e *RoleService_Expecter) Create(ctx interface{}, req interface{}) *RoleService_Create_Call {
	return &RoleService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *RoleService_Create_Call) Run(run func(ctx context.Context, req role.CreateRoleRequest)) *RoleService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 role.CreateRoleRequest
		if args[1] != nil {
			arg1 = args[1].(role.CreateRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleService_Create_Call) Return(role1 *role.Role, err error) *RoleService_Create_Call {
	_c.Call.Return(role1, err)
	return _c
}

func (_c *RoleService_Create_Call) RunAndReturn(run func(ctx context.Context, req role.CreateRoleRequest) (*role.Role, error)) *RoleService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type RoleService
func (_mock *RoleService) GetByID(ctx context.Context, id string) (*role.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*role.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *role.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RoleService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RoleService_Expecter) GetByID(ctx interface{}, id interface{}) *RoleService_GetByID_Call {
	return &RoleService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RoleService_GetByID_Call) Run(run func(ctx context.Context, id string)) *RoleService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleService_GetByID_Call) Return(role1 *role.Role, err error) *RoleService_GetByID_Call {
	_c.Call.Return(role1, err)
	return _c
}

func (_c *RoleService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*role.Role, error)) *RoleService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type RoleService
func (_mock *RoleService) List(ctx context.Context) ([]*role.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*role.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*role.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RoleService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleService_Expecter) List(ctx interface{}) *RoleService_List_Call {
	return &RoleService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *RoleService_List_Call) Run(run func(ctx context.Context)) *RoleService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleService_List_Call) Return(roles []*role.Role, err error) *RoleService_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RoleService_List_Call) RunAndReturn(run func(ctx context.Context) ([]*role.Role, error)) *RoleService_List_Call {
	_c.Call.Return(run)
	return _c
}
