// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rock288/go-mongo-boilerplate/internal/role"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// NewRoleRepository creates a new instance of RoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepository {
	mock := &RoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

type RoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleRepository) EXPECT() *RoleRepository_Expecter {
	return &RoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RoleRepository
func (_mock *RoleRepository) Create(ctx context.Context, r *role.Role) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *role.Role) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *role.Role
func (_e *RoleRepository_Expecter) Create(ctx interface{}, r interface{}) *RoleRepository_Create_Call {
	return &RoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *RoleRepository_Create_Call) Run(run func(ctx context.Context, r *role.Role)) *RoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *role.Role
		if args[1] != nil {
			arg1 = args[1].(*role.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_Create_Call) Return(err error) *RoleRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RoleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, r *role.Role) error) *RoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function for the type RoleRepository
func (_mock *RoleRepository) ExistsByName(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type RoleRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *RoleRepository_Expecter) ExistsByName(ctx interface{}, name interface{}) *RoleRepository_ExistsByName_Call {
	return &RoleRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name)}
}

func (_c *RoleRepository_ExistsByName_Call) Run(run func(ctx context.Context, name string)) *RoleRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_ExistsByName_Call) Return(b bool, err error) *RoleRepository_ExistsByName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *RoleRepository_ExistsByName_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *RoleRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type RoleRepository
func (_mock *RoleRepository) FindByID(ctx context.Context, id bson.ObjectID) (*role.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (*role.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) *role.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type RoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *RoleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *RoleRepository_FindByID_Call {
	return &RoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *RoleRepository_FindByID_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *RoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_FindByID_Call) Return(role1 *role.Role, err error) *RoleRepository_FindByID_Call {
	_c.Call.Return(role1, err)
	return _c
}

func (_c *RoleRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID) (*role.Role, error)) *RoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type RoleRepository
func (_mock *RoleRepository) FindByName(ctx context.Context, name string) (*role.Role, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*role.Role, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *role.Role); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type RoleRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *RoleRepository_Expecter) FindByName(ctx interface{}, name interface{}) *RoleRepository_FindByName_Call {
	return &RoleRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *RoleRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *RoleRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_FindByName_Call) Return(role1 *role.Role, err error) *RoleRepository_FindByName_Call {
	_c.Call.Return(role1, err)
	return _c
}

func (_c *RoleRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*role.Role, error)) *RoleRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type RoleRepository
func (_mock *RoleRepository) List(ctx context.Context) ([]*role.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*role.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*role.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*role.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*role.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleRepository_Expecter) List(ctx interface{}) *RoleRepository_List_Call {
	return &RoleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *RoleRepository_List_Call) Run(run func(ctx context.Context)) *RoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleRepository_List_Call) Return(roles []*role.Role, err error) *RoleRepository_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RoleRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*role.Role, error)) *RoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
