// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sqs/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMessageHandler creates a new instance of MessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageHandler {
	mock := &MessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MessageHandler is an autogenerated mock type for the MessageHandler type
type MessageHandler struct {
	mock.Mock
}

type MessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageHandler) EXPECT() *MessageHandler_Expecter {
	return &MessageHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MessageHandler
func (_mock *MessageHandler) Handle(ctx context.Context, msg *types.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MessageHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MessageHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *types.Message
func (_e *MessageHandler_Expecter) Handle(ctx interface{}, msg interface{}) *MessageHandler_Handle_Call {
	return &MessageHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, msg)}
}

func (_c *MessageHandler_Handle_Call) Run(run func(ctx context.Context, msg *types.Message)) *MessageHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.Message
		if args[1] != nil {
			arg1 = args[1].(*types.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MessageHandler_Handle_Call) Return(err error) *MessageHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MessageHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, msg *types.Message) error) *MessageHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}
