// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rock288/go-mongo-boilerplate/internal/platform/sqs"
	mock "github.com/stretchr/testify/mock"
)

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type Producer
func (_mock *Producer) Publish(ctx context.Context, queueURL string, body string, opts ...sqs.PublishOpt) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, queueURL, body, opts)
	} else {
		tmpRet = _mock.Called(ctx, queueURL, body)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...sqs.PublishOpt) error); ok {
		r0 = returnFunc(ctx, queueURL, body, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Producer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
//   - body string
//   - opts ...sqs.PublishOpt
func (_e *Producer_Expecter) Publish(ctx interface{}, queueURL interface{}, body interface{}, opts ...interface{}) *Producer_Publish_Call {
	return &Producer_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, queueURL, body}, opts...)...)}
}

func (_c *Producer_Publish_Call) Run(run func(ctx context.Context, queueURL string, body string, opts ...sqs.PublishOpt)) *Producer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []sqs.PublishOpt
		var variadicArgs []sqs.PublishOpt
		if len(args) > 3 {
			variadicArgs = args[3].([]sqs.PublishOpt)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *Producer_Publish_Call) Return(err error) *Producer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Publish_Call) RunAndReturn(run func(ctx context.Context, queueURL string, body string, opts ...sqs.PublishOpt) error) *Producer_Publish_Call {
	_c.Call.Return(run)
	return _c
}
