// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rock288/go-mongo-boilerplate/internal/platform/config"
	"github.com/rock288/go-mongo-boilerplate/internal/platform/database"
	"github.com/rock288/go-mongo-boilerplate/internal/platform/httpserver"
	"github.com/rock288/go-mongo-boilerplate/internal/platform/logger"
	"github.com/rock288/go-mongo-boilerplate/internal/role"
	"github.com/rock288/go-mongo-boilerplate/internal/user"
)

// Injectors from wire.go:

func InitializeServer(cfgPath string) (*ServerApp, func(), error) {
	configConfig, err := config.Load(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	loggerConfig := ProvideLoggerConfig(configConfig)
	slogLogger := logger.New(loggerConfig)
	mongoConfig := ProvideMongoConfig(configConfig)
	observabilityConfig := ProvideObservabilityConfig(configConfig)
	client, cleanup, err := database.NewMongoClient(mongoConfig, observabilityConfig)
	if err != nil {
		return nil, nil, err
	}
	serverConfig := ProvideServerConfig(configConfig)
	server := httpserver.New(serverConfig)
	registry := ProvideHealthRegistry(client)
	mongoDatabase := database.NewDatabase(client, mongoConfig)
	userRepository := user.NewUserRepository(mongoDatabase)
	userService := user.NewUserService(userRepository)
	userHandler := user.NewUserHandler(userService)
	roleRepository := role.NewRoleRepository(mongoDatabase)
	roleService := role.NewRoleService(roleRepository)
	roleHandler := role.NewRoleHandler(roleService)
	engine := ProvideRouter(server, slogLogger, configConfig, registry, userHandler, roleHandler)
	shutdown, cleanup2, err := ProvideObservability(observabilityConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serverApp := &ServerApp{
		Config:   configConfig,
		Logger:   slogLogger,
		Mongo:    client,
		Server:   server,
		Router:   engine,
		Health:   registry,
		Shutdown: shutdown,
	}
	return serverApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var platformSet = wire.NewSet(config.Load, ProvideServerConfig,
	ProvideMongoConfig,
	ProvideLoggerConfig,

	ProvideObservabilityConfig,

	ProvideCORSConfig,
	ProvideRateLimitConfig,

	ProvideObservability, logger.New, database.NewMongoClient, database.NewDatabase, httpserver.New, ProvideHealthRegistry,
)
